# Cheatsheet:
# https://gist.github.com/MohamedAlaa/2961058
#
# C-b:
# % split pane vertically
# " split pane horizontally
# x close pane
# Arrows move pane
# c new window
# n next window
# p prev window
# & close window
#set -g default-terminal "screen-256color"
set -g default-terminal "xterm-256color"

# C-b m, enter to set a session as the main one
bind-key m command-prompt -I "rename-session main"

# C-b a, enter to attach to main session (C-b d to detach)
bind-key a command-prompt -I "attach -t main"

# C-b d, enter to detach (but immediately open a new client)
bind-key d command-prompt -I "detach-client -E 'exec tmx2'"

# More scrollback
set -g history-limit 25000

# more intuitive keybindings for splitting
bind h split-window -v -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"

# CTRL + arrow keys move between words and all
set-window-option -g xterm-keys on

# Vi like keys for copy mode
# List the keys with `tmux list-keys -T copy-mode-vi`
set-window-option -g mode-keys vi

# Do not copy selection and cancel copy mode on drag end event
# Prefer iTerm style selection: select, then mouse click to copy to buffer
#unbind -T copy-mode-vi MouseDragEnd1Pane
#bind -T copy-mode-vi MouseDown1Pane select-pane \;\
#  send-keys -X copy-pipe "pbcopy" \;\
#  send-keys -X clear-selection

# Don't keep around unattached clients
# set -g destroy-unattached on

# Use p to paste and ctrl + p to select what to paste
bind p paste-buffer
bind C-p choose-buffer

# Sanity with mouse (esp. scrolling)
set -g mouse on
#bind-key m set-option -g mouse on \; display 'Mouse: ON'
#bind-key M set-option -g mouse off \; display 'Mouse: OFF'

set -g pane-border-status top
set -g pane-border-format '#P: #{pane_current_command}@#{pane_current_path} #(~/bin/citc-client.sh #{pane_current_path} -d -b)'

set -g set-titles-string '[#S] #P: #{pane_current_command}@#{pane_current_path} #(~/bin/citc-client.sh #{pane_current_path} -d -b)'
set -g set-titles on

# Reload this file with C-b C-R
bind R source-file ~/.tmux.conf \; display-message "Config reloaded..."

# Tmux powerline
set-option -g status on
set-option -g status-interval 2
set-option -g status-justify "centre"
set-option -g status-left-length 60
set-option -g status-right-length 90
set-option -g status-left "#(~/tmux-powerline/powerline.sh left)"
set-option -g status-right "#(~/tmux-powerline/powerline.sh right)"

# Colours
set -g pane-border-style fg=default,bg=default
set -g pane-active-border-style fg=colour129,bg=default
set -g status-style fg=colour0,bg=colour177

# Plugins
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @continuum-restore 'on'
set -g @continuum-boot 'on'

set -g @resurrect-save-shell-history 'on'
set -g @resurrect-capture-pane-contents 'on'

set -g @resurrect-strategy-vim 'session'

